/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-07-17 12:46:57 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/trigramdb -t trigramentry -s public
 *
 */


export namespace trigramentryFields {
    export type id = number;
    export type filename = string;
    export type content = string;

}

export interface trigramentry {
    id: trigramentryFields.id;
    filename: trigramentryFields.filename;
    content: trigramentryFields.content;

}
